<?php

########################################################################
# Extension Manager/Repository config file for ext: "cookiecontrol"
#
# Auto generated by Extension Builder 2013-01-07
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'cookiecontrol',
	'description' => 'cookiecontrol',
	'category' => 'plugin',
	'author' => 'Azeef, Sivaprasad.s',
	'author_email' => 'azeef@pitsolutions.com,sivaprasad.s@pitsolutions.com',
	'author_company' => 'PIT Solutions',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3',
			'fluid' => '1.3',
			'typo3' => '4.5',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>